"use strict";

const PROFILE_VERSION = 1;
const MAX_BODY_BYTES = 24 * 1024 * 1024;
const MAX_ACCOUNTS = 25;
const MAX_CHARACTERS_PER_ACCOUNT = 25;
const MAX_RAID_BREAKDOWNS_PER_CHAR = 40;
const MAX_TOP_SKILLS_PER_CHAR = 8;
const MAX_TOP_SOURCES_PER_CHAR = 8;
const MAX_BUILD_VARIANTS_PER_CHAR = 8;
const MAX_ENGRAVINGS_PER_CHAR = 8;
const MAX_ARK_PASSIVE_NODES_PER_TREE = 40;
const MAX_ENCOUNTER_SUMMARIES_PER_SYNC = 5000;
const MAX_TOP_SKILLS_PER_ENCOUNTER = 5;

module.exports = {
  MAX_ACCOUNTS,
  MAX_ARK_PASSIVE_NODES_PER_TREE,
  MAX_BODY_BYTES,
  MAX_BUILD_VARIANTS_PER_CHAR,
  MAX_CHARACTERS_PER_ACCOUNT,
  MAX_ENCOUNTER_SUMMARIES_PER_SYNC,
  MAX_ENGRAVINGS_PER_CHAR,
  MAX_RAID_BREAKDOWNS_PER_CHAR,
  MAX_TOP_SKILLS_PER_CHAR,
  MAX_TOP_SKILLS_PER_ENCOUNTER,
  MAX_TOP_SOURCES_PER_CHAR,
  PROFILE_VERSION,
};
