"use strict";

const AUTO_MANAGE_GATHER_CHARACTER_CONCURRENCY = 2;
const PUBLIC_LOG_DISABLED_REPROBE_MS = 24 * 60 * 60 * 1000;

module.exports = {
  AUTO_MANAGE_GATHER_CHARACTER_CONCURRENCY,
  PUBLIC_LOG_DISABLED_REPROBE_MS,
};
