"use strict";

const SESSION_TTL_MS = 5 * 60 * 1000;
const GOLD_EARNER_CAP_PER_ACCOUNT = 6;
const PICKER_MAX_OPTIONS = 20;
const BUTTONS_PER_ROW = 5;

const CHECK_ICON = "\uD83D\uDCB0";
const UNCHECK_ICON = "\u2B1C";

module.exports = {
  SESSION_TTL_MS,
  GOLD_EARNER_CAP_PER_ACCOUNT,
  PICKER_MAX_OPTIONS,
  BUTTONS_PER_ROW,
  CHECK_ICON,
  UNCHECK_ICON,
};
