"use strict";

const CHARACTER_PROFILE_STATS_KEYS = [
  "encounters",
  "allEncounterCount",
  "supportLogCount",
  "dpsBuildLogCount",
  "supportLogRate",
  "dpsBuildLogRate",
  "primaryRoleRate",
  "firstFightStart",
  "lastFightStart",
  "avgDurationMs",
  "avgActiveDurationMs",
  "avgIntermissionMs",
  "avgActiveTimeRate",
  "avgDps",
  "medianDps",
  "p75Dps",
  "p90Dps",
  "avgPeak10sDps",
  "p90Peak10sDps",
  "avgBurstRatio",
  "avgRdps",
  "medianRdps",
  "avgNdps",
  "medianNdps",
  "avgDamageShare",
  "medianDamageShare",
  "avgTopDamageProximity",
  "contextCoverageRate",
  "contextSampleCountAvg",
  "avgContextPerformancePercentile",
  "avgContextDamageSharePercentile",
  "avgContextTopDamageProximityPercentile",
  "avgContextSupportPercentile",
  "topRate",
  "avgRank",
  "partyCountAvg",
  "deathlessRate",
  "deathRate",
  "totalDeaths",
  "avgDeaths",
  "totalDeadTimeMs",
  "avgDeadTimeMs",
  "avgDeadTimeRate",
  "rdpsValidCount",
  "rdpsValidRate",
  "avgSupporterPercent",
  "medianSupporterPercent",
  "radiantSupportCount",
  "radiantSupportRate",
  "avgSupporterDamageGivenPerMinute",
  "avgRdpsDamageGivenShare",
  "supporterRankValidCount",
  "supporterCompetitiveCount",
  "avgSupporterRank",
  "supporterCountAvg",
  "supporterTopRate",
  "avgCounters",
  "avgCastsPerMinute",
  "avgHitsPerMinute",
  "avgCritRate",
  "avgCritDamageShare",
  "avgBackAttackRate",
  "avgFrontAttackRate",
  "avgBackAttackDamageShare",
  "avgFrontAttackDamageShare",
  "avgPositionalDamageShare",
  "avgDamageTaken",
  "avgDamageTakenPerMinute",
  "damageTakenShareValidCount",
  "avgDamageTakenShare",
  "avgDamageAbsorbedPerMinute",
  "avgShieldReceivedPerMinute",
  "avgStagger",
  "avgStaggerPerMinute",
  "avgIncapacitations",
  "avgIncapacitationsPerMinute",
  "avgHyperShare",
  "avgUnbuffedShare",
  "avgUnbuffedDps",
  "avgSupportBuffedShare",
  "avgSupportDebuffedShare",
  "avgPartyBuffedShare",
  "avgSelfBuffedShare",
  "avgPartyDebuffedShare",
  "avgBattleItemDebuffedShare",
  "avgSkillCount",
  "avgTopSkillShare",
  "avgRdpsDamageGiven",
  "avgRdpsDamageGivenPerMinute",
  "avgRdpsDamageReceivedSupport",
  "avgRdpsDamageReceivedSupportPerMinute",
  "avgSynergyGiven",
  "avgSynergyGivenPerMinute",
  "avgSynergyGivenShare",
  "avgSynergyReceivedShare",
  "avgSupportAp",
  "avgSupportBrand",
  "avgSupportIdentity",
  "avgSupportHyper",
  "avgProtection",
  "avgProtectionPerMinute",
  "avgGearScore",
  "latestGearScore",
  "avgCombatPower",
  "latestCombatPower",
  "arkPassiveRate",
  "buildVariantCount",
  "unclassifiedBuildLogCount",
  "consistency",
];

const CHARACTER_PROFILE_PERCENT_STATS = [
  "deathRate",
  "avgTopDamageProximity",
  "contextCoverageRate",
  "avgContextPerformancePercentile",
  "avgContextDamageSharePercentile",
  "avgContextTopDamageProximityPercentile",
  "avgContextSupportPercentile",
  "avgBurstRatio",
  "avgDeadTimeRate",
  "rdpsValidRate",
  "avgSupporterPercent",
  "medianSupporterPercent",
  "radiantSupportRate",
  "avgRdpsDamageGivenShare",
  "avgActiveTimeRate",
  "supporterTopRate",
  "avgCritDamageShare",
  "avgBackAttackDamageShare",
  "avgFrontAttackDamageShare",
  "avgPositionalDamageShare",
  "avgDamageTakenShare",
  "avgSynergyGivenShare",
  "arkPassiveRate",
  "supportLogRate",
  "dpsBuildLogRate",
  "primaryRoleRate",
];

const CHARACTER_PROFILE_COUNT_STATS = [
  "contextSampleCountAvg",
  "totalDeaths",
  "rdpsValidCount",
  "radiantSupportCount",
  "supporterRankValidCount",
  "supporterCompetitiveCount",
  "damageTakenShareValidCount",
  "unclassifiedBuildLogCount",
  "allEncounterCount",
  "supportLogCount",
  "dpsBuildLogCount",
];

const CHARACTER_PROFILE_BUFF_SHARE_STATS = [
  "avgSupportBuffedShare",
  "avgSupportDebuffedShare",
  "avgPartyBuffedShare",
  "avgSelfBuffedShare",
  "avgPartyDebuffedShare",
  "avgBattleItemDebuffedShare",
];

const CHARACTER_PROFILE_STATS_CLAMP_RULES = [
  [CHARACTER_PROFILE_PERCENT_STATS, { max: 100 }],
  [CHARACTER_PROFILE_COUNT_STATS, { max: 100000 }],
  [["avgDeaths", "avgSupporterRank", "supporterCountAvg", "buildVariantCount"], { max: 1000 }],
  [["totalDeadTimeMs", "avgDeadTimeMs"], { max: 9999999999999 }],
  [["avgDurationMs", "avgActiveDurationMs", "avgIntermissionMs"], { max: 24 * 60 * 60 * 1000 }],
  [["avgGearScore", "latestGearScore"], { max: 9999 }],
  [CHARACTER_PROFILE_BUFF_SHARE_STATS, { max: 999 }],
];

const CHARACTER_PROFILE_SCORE_KEYS = [
  "overall",
  "mvp",
  "output",
  "damageShare",
  "rank",
  "context",
  "consistency",
  "survival",
  "mechanics",
  "supportUptime",
  "raidContribution",
  "supportRank",
  "protection",
];

module.exports = {
  CHARACTER_PROFILE_STATS_KEYS,
  CHARACTER_PROFILE_STATS_CLAMP_RULES,
  CHARACTER_PROFILE_SCORE_KEYS,
};
